# Generated by Django 6.0 on 2025-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300)),
                ("cep", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Residencial", "Residencial"),
                            ("Comercial", "Comercial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("iptu_inscription", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
